### ISSUE TITLE
Naming and bin/hex

### ISSUE THREAD

**Issue by jcw** [karlp/libopencm3-miniblink#2]
Would it be an idea to also optionally generate `.bin` and `.hex` files?

These images can be a great tool to quickly validate the next step, i.e. uploading and running. One approach could be to rename the `bin/` directory to `build/` (it's not really a "bin" you'd want to add to any PATH env, after all), and then create extra pseudo targets for "bin" and "hex" to build the requested format for all the images.

A full build for testing then becomes this one-liner: `make all bin hex`

**Comment by karlp** [comment]
I'm not against generating bin's, but I'd like to see more people realise that they can get better behaviour using .elf files, with less error prone steps like remembering what address to flash to.  The whole "how to flash" section is the last real piece of this repo, as it's massively openended.

I _certainly_ don't see any reason for _both_ bin and hex :)

**Comment by jcw** [comment]
Well, st-flash wants .bin files, wherease stm32flash wants hex files. In GDB, hex is easier than bin.
Sure, there is elf for debugging - but if you want to do over-the-air updates, you want bin.
The address is always the same on stm32.

**Comment by karlp** [comment]
in gdb, you just use elf.  also, there's far more than stm32 supported here :) I've got ti, silabs, atmel/microchip parts as well to come in :)  And like I said, I'm philosophically opposed to letting people keep using stone age tools :)

**Comment by jcw** [comment]
"Stone age tools": that's neither argument nor philosphy, that's opinion. Goodbye.

**Comment by karlp** [comment]
Look I'm not against it, I know they're still heavily used, I just want people to know that are are other, arguably better options.  Like I said, the whole "how to flash" the files generated here is still a hairy open problem.  The boards with integrated debuggers are "easy" but the rest are hairy.

**Comment by jcw** [comment]
Your perspective is development, this was about deployment. Let’s not dwell on it, life’s too short.

**Comment by karlp** [comment]
fixed in https://github.com/karlp/libopencm3-miniblink/commit/31a01d388411e02a708746aa6f7e443e269aee2f thanks for the push

**Comment by jcw** [comment]
Thanks. I appreciate your willingness to make such a change despite your reservations.
